src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/discord/ChannelInfoCommand.kt
=> 🐛 | Corrigir pequeno bug no tópico do "+channelinfo"

src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/minecraft/McQueryCommand.kt, src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/minecraft/PeQueryCommand.kt
`mcquery` and `pequery` commands now use the locale.
=> Localization in pequery and mcquery

src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/economy/PagarCommand.kt
=> Adicionar um usage ao +pagar

src/main/java/com/mrpowergamerbr/loritta/utils/LorittaUtilsKotlin.kt
=> Sorry again

src/main/java/com/mrpowergamerbr/loritta/modules/InviteLinkModule.kt
https://i.imgur.com/dbqxEAn.png
=> Corrigir bug na verificação de convites

src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/utils/PackageInfoCommand.kt
Sintaxe:
```json
{
"date": "2018-09-11",
"time": "12:34:00",
"state": "Objeto aceite",
"locations": [
{
"state": "Aceitação",
"reason": "-",
"location": "SANTA MARTA (LISBOA)",
"reciever": "-",
"date": "11-09-2018",
"time": "12:34:00"
}
]
}
```
=> Alterações na API dos CTT

src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/actions/ActionCommand.kt, src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/actions/AttackCommand.kt, src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/actions/DanceCommand.kt, src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/actions/HugCommand.kt, src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/actions/KissCommand.kt, src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/actions/SlapCommand.kt, src/main/java/com/mrpowergamerbr/loritta/utils/locale/BaseLocale.kt
Para evitar garotos espertinhos
=> quem tentar dar tapa na Loritta vai levar de volta

src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/administration/BanCommand.kt, src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/administration/KickCommand.kt, src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/administration/WarnCommand.kt
=> Adicionar "| s" aos comandos de punição

src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/administration/LockCommand.kt, src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/administration/UnlockCommand.kt
Fix #200 
Sorry for the 3 Pull Request
=> Lock Command

pom.xml, src/main/java/com/mrpowergamerbr/loritta/commands/CommandManager.kt, src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/administration/DashboardCommand.kt, src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/images/AtendenteCommand.kt, src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/misc/MagicPingCommand.kt, src/main/java/com/mrpowergamerbr/loritta/utils/Constants.kt, src/main/java/com/mrpowergamerbr/loritta/utils/MessageUtils.kt, src/main/java/net/perfectdreams/commands/loritta/LorittaCommand.kt, src/main/java/net/perfectdreams/commands/loritta/LorittaCommandContext.kt, src/main/java/net/perfectdreams/commands/loritta/LorittaCommandManager.kt
* Comando sugerido por Inácio Oliveira#0007 (174950526700617729)
https://i.imgur.com/cob9GKC.png
* Se o comando for executado em mensagem direta (ou guildas onde o usuário não tem permissão de configurar o Dashboard ou de "Gerenciar servidor"), a Lori vai mandar o link onde o usuário pode escolher qual servidor ele vai adicionar/configurar.
* Link da Pull Request das strings do comando: https://github.com/LorittaBot/LorittaLocales/pull/11
=> Adicionar o comando '+dashboard'

src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/actions/SlapCommand.kt, src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/administration/DashboardCommand.kt
simples de troca de fun pra val 🤷‍♂️ 
por causa desse erro na compilação:
=> Pequeno fix no DashboardCommand.kt

src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/utils/EmojiSearchCommand.kt
=> Adicionar uma alias ao buscaremoji

loritta-plugins/artsy-joy-lori/src/main/kotlin/net/perfectdreams/loritta/ArtsyJoyLori.kt, loritta-plugins/artsy-joy-lori/src/main/kotlin/net/perfectdreams/loritta/commands/discord/GuildBannerCommand.kt
https://github.com/LorittaBot/LorittaLocales/pull/27/
=> +guildbanner

loritta-core/src/main/java/com/mrpowergamerbr/loritta/audio/AudioManager.kt
Isto deve evitar rate limits do YouTube.
=> Pesquisar músicas pelo Lavalink em vez de pesquisar localmente

loritta-core/src/main/java/com/mrpowergamerbr/loritta/audio/AudioManager.kt
Para evitar spammar a API do YouTube
=> Implementar cache de tracks do Lavalink

loritta-core/src/main/java/com/mrpowergamerbr/loritta/Loritta.kt, loritta-core/src/main/java/com/mrpowergamerbr/loritta/listeners/ChannelListener.kt, loritta-core/src/main/java/com/mrpowergamerbr/loritta/listeners/DiscordListener.kt, loritta-core/src/main/java/com/mrpowergamerbr/loritta/listeners/EventLogListener.kt, loritta-core/src/main/java/com/mrpowergamerbr/loritta/listeners/MessageListener.kt, loritta-core/src/main/java/com/mrpowergamerbr/loritta/listeners/VoiceChannelListener.kt, loritta-core/src/main/java/com/mrpowergamerbr/loritta/threads/RemindersThread.kt, loritta-core/src/main/java/com/mrpowergamerbr/loritta/utils/BomDiaECia.kt, loritta-core/src/main/java/com/mrpowergamerbr/loritta/utils/LorittaLandRoleSync.kt
**ID da conta secundária:** 494237647678734356
=> Caso o bot esteja sendo usado como backup, ignore caso o bot principal esteja online

loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/music/LyricsCommand.kt
=> Fix +lyrics not getting the right div element from letras.mus

loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/administration/LimparCommand.kt
Pinned messages will be deleted only if user use the force flag.
=> Don't delete pinned messages in Clear Command

README.md, loritta-discord/src/main/java/net/perfectdreams/loritta/platform/discord/LorittaDiscord.kt
Locales are now automatically downloaded so that people selfhosting Loritta won't need to have the hassle to download the locales from another repository.
=> Automatically download locales

loritta-discord/src/main/java/com/mrpowergamerbr/loritta/utils/config/GeneralConfig.kt, loritta-discord/src/main/java/com/mrpowergamerbr/loritta/utils/config/PicPayConfig.kt, loritta-discord/src/main/java/net/perfectdreams/loritta/utils/payments/PaymentGateway.kt, loritta-discord/src/main/java/net/perfectdreams/loritta/website/DefaultRoutes.kt, loritta-discord/src/main/java/net/perfectdreams/loritta/website/routes/api/v1/callbacks/PostMercadoPagoCallbackRoute.kt, loritta-discord/src/main/java/net/perfectdreams/loritta/website/routes/api/v1/callbacks/PostPicPayCallbackRoute.kt, loritta-discord/src/main/java/net/perfectdreams/loritta/website/routes/api/v1/economy/PostBundlesRoute.kt, loritta-discord/src/main/java/net/perfectdreams/loritta/website/routes/api/v1/user/PostDonationPaymentRoute.kt, loritta-discord/src/main/resources/loritta.conf, loritta-website/spicy-morenitta/src/main/kotlin/net/perfectdreams/spicymorenitta/routes/DonateRoute.kt, loritta-website/spicy-morenitta/src/main/kotlin/net/perfectdreams/spicymorenitta/routes/user.dashboard/AvailableBundlesDashboardRoute.kt, loritta-website/spicy-morenitta/src/main/kotlin/net/perfectdreams/spicymorenitta/utils/PaymentUtils.kt
Adds PicPay support, not really tested because PicPay doesn't have an way to test payments, but it should work fine.
Fixes #2115
=> Add PicPay support

loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/music/LyricsCommand.kt, loritta-plugins/mal-commands/build.gradle.kts, loritta-plugins/mal-commands/src/main/kotlin/net/perfectdreams/loritta/plugin/malcommands/MalCommandsPlugin.kt, loritta-plugins/mal-commands/src/main/kotlin/net/perfectdreams/loritta/plugin/malcommands/commands/MalAnimeCommand.kt, loritta-plugins/mal-commands/src/main/kotlin/net/perfectdreams/loritta/plugin/malcommands/commands/base/DSLCommandBase.kt, loritta-plugins/mal-commands/src/main/kotlin/net/perfectdreams/loritta/plugin/malcommands/util/MalAnime.kt, loritta-plugins/mal-commands/src/main/kotlin/net/perfectdreams/loritta/plugin/malcommands/util/MalConstants.kt, loritta-plugins/mal-commands/src/main/kotlin/net/perfectdreams/loritta/plugin/malcommands/util/MalScrappingUtils.kt, loritta-plugins/mal-commands/src/main/kotlin/net/perfectdreams/loritta/plugin/malcommands/util/MalUtils.kt, loritta-plugins/mal-commands/src/main/resources/plugin.yml, settings.gradle.kts
Should be used for MAL commands, like +malanime, +malmanga (not implemented scrapping for mangas yet)
~~ignore the first commit name, i meant implementation of scrapping not "commands"~~
Things I implemented: querying animes, anime info
=> Implementation of MyAnimeList scrapping (specifically for +malanime) 

loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/administration/QuickPunishmentCommand.kt, loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/administration/WarnListCommand.kt, loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/discord/BotInfoCommand.kt, loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/discord/ChannelInfoCommand.kt, loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/discord/EmojiCommand.kt, loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/discord/ServerIconCommand.kt, loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/discord/ServerInfoCommand.kt, loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/discord/UserInfoCommand.kt, loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/fun/AvaliarWaifuCommand.kt, loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/fun/ShipCommand.kt, loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/images/AmizadeCommand.kt, loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/images/GetOverHereCommand.kt, loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/images/JoojCommand.kt, loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/images/ManiaTitleCardCommand.kt, loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/images/NyanCatCommand.kt, loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/images/OjjoCommand.kt, loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/minecraft/McAvatarCommand.kt, loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/minecraft/McBodyCommand.kt, loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/minecraft/McHeadCommand.kt, loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/minecraft/McMoletomCommand.kt, loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/minecraft/McSkinCommand.kt, loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/minecraft/SpigotMcCommand.kt, loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/utils/AnagramaCommand.kt, loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/utils/CalculadoraCommand.kt, loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/utils/ColorInfoCommand.kt, loritta-discord/src/main/java/com/mrpowergamerbr/loritta/utils/Constants.kt
Not really finished and I will probably merge this before everything is migrated
=> Remove Legacy Locale

loritta-api/src/commonMain/kotlin/net/perfectdreams/loritta/utils/Emotes.kt, loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/discord/UserInfoCommand.kt, loritta-discord/src/main/java/net/perfectdreams/loritta/platform/discord/utils/UserFlagBadgeEmotes.kt
You can see your badges that appear in your discord profile in the +userinfo embed.
=> Added discord user badges in +userinfo

loritta-api/src/commonMain/kotlin/net/perfectdreams/loritta/utils/Emotes.kt, loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/discord/UserInfoCommand.kt, loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/images/TodoGrupoTemCommand.kt, loritta-discord/src/main/java/net/perfectdreams/loritta/platform/discord/utils/UserFlagBadgeEmotes.kt, loritta-plugins/artsy-joy-lori/src/main/kotlin/net/perfectdreams/loritta/commands/images/TristeRealidadeCommand.kt
Suggestion was made in Loritta's Apartment (BR), by foguw#8368 (449940691045318656)
=> Removed bots in +sadreality and +everygrouphas

loritta-plugins/mal-commands/src/main/kotlin/net/perfectdreams/loritta/plugin/malcommands/commands/MalAnimeCommand.kt, loritta-plugins/mal-commands/src/main/kotlin/net/perfectdreams/loritta/plugin/malcommands/commands/models/MalAnime.kt, loritta-plugins/mal-commands/src/main/kotlin/net/perfectdreams/loritta/plugin/malcommands/exceptions/MalException.kt, loritta-plugins/mal-commands/src/main/kotlin/net/perfectdreams/loritta/plugin/malcommands/exceptions/MalSearchException.kt, loritta-plugins/mal-commands/src/main/kotlin/net/perfectdreams/loritta/plugin/malcommands/util/MalConstants.kt, loritta-plugins/mal-commands/src/main/kotlin/net/perfectdreams/loritta/plugin/malcommands/util/MalScrappingUtils.kt, loritta-plugins/mal-commands/src/main/kotlin/net/perfectdreams/loritta/plugin/malcommands/util/MalUtils.kt
* implements exceptions to better debugging (better understanding of what gone wrong)
* fixes command error when parsing animes with "unknown" episodes
* better logging
* query scrapping: now it uses regular expressions to make sure that we got the right page to parse
=> +malanime: Better debugging and fix when parsing animes with "unknown" episodes

loritta-plugins/helping-hands/src/main/kotlin/net/perfectdreams/loritta/plugin/helpinghands/commands/RepListCommand.kt
* Reformatted code and optimized imports
* Fixes +replist error when its embed content bypasses 2048 chars limit
=> Fix +replist command

loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/misc/PingCommand.kt
I don't understand why it was used in the first place, sorry if this PR is useless
=> replace unnecessary string builder in PingCommand.kt

loritta-discord/src/main/java/com/mrpowergamerbr/loritta/listeners/MessageListener.kt
=> Ignore if message is/was pinned and if it was sent before 15 minutes ago

loritta-discord/src/main/java/net/perfectdreams/loritta/commands/vanilla/fun/GiveawaySetupCommand.kt
Verify if Loritta has permission to react/send embeds/see channel history in the selectioned channel on GiveawaySetupCommand.kt
=> Fixes some permissions errors

loritta-plugins/mal-commands/src/main/kotlin/net/perfectdreams/loritta/plugin/malcommands/commands/MalAnimeCommand.kt, loritta-plugins/mal-commands/src/main/kotlin/net/perfectdreams/loritta/plugin/malcommands/exceptions/MalException.kt, loritta-plugins/mal-commands/src/main/kotlin/net/perfectdreams/loritta/plugin/malcommands/exceptions/MalSearchException.kt, loritta-plugins/mal-commands/src/main/kotlin/net/perfectdreams/loritta/plugin/malcommands/models/MalAnime.kt, loritta-plugins/mal-commands/src/main/kotlin/net/perfectdreams/loritta/plugin/malcommands/util/MalConstants.kt, loritta-plugins/mal-commands/src/main/kotlin/net/perfectdreams/loritta/plugin/malcommands/util/MalScrappingUtils.kt, loritta-plugins/mal-commands/src/main/kotlin/net/perfectdreams/loritta/plugin/malcommands/util/MalUtils.kt
Title self-explanatory. I also did some refactors
=> Fix +anime scrapping

loritta-discord/src/main/java/com/mrpowergamerbr/loritta/threads/UpdateStatusThread.kt, loritta-discord/src/main/java/com/mrpowergamerbr/loritta/utils/config/DiscordConfig.kt
=> Sometimes it is nice to know how to write

loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/utils/PackageInfoCommand.kt
=> Fix double mention on PackageInfoCommand.kt 

loritta-discord/src/main/java/com/mrpowergamerbr/loritta/threads/RemindersThread.kt, loritta-discord/src/main/java/com/mrpowergamerbr/loritta/utils/Constants.kt, loritta-discord/src/main/java/com/mrpowergamerbr/loritta/utils/MessageUtils.kt
See: Issue #2176 
When a reminder goes off, users can click the :zzz: reaction to be reminded again in 10 minutes.
=> Add a reminder "snooze" button

loritta-discord/src/main/java/com/mrpowergamerbr/loritta/threads/RemindersThread.kt
Implements the improvements you suggested, let me know if the instruction text is good.
=> Add snooze instructions to reminders

loritta-discord/src/main/java/com/mrpowergamerbr/loritta/listeners/EventLogListener.kt
please work please work please work please work please work please work please work please work
=> add user id to deleted messages event log

loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/misc/LanguageCommand.kt
* Also re-formats +language code
* Also adds a tip that personal language exists if the command was executed in guilds
Locales: https://github.com/LorittaBot/LorittaLocales/pull/102
=> Implement resetting/removal option of personal language

loritta-plugins/artsy-joy-lori/src/main/kotlin/net/perfectdreams/loritta/commands/actions/modern/ActionCommands.kt
=> Fix some bugs at action commands

loritta-discord/src/main/java/com/mrpowergamerbr/loritta/Loritta.kt, loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/CommandContext.kt, loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/administration/AdminUtils.kt, loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/administration/BanCommand.kt, loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/administration/KickCommand.kt, loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/administration/LimparCommand.kt, loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/administration/LockCommand.kt, loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/administration/MuteCommand.kt, loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/administration/RoleIdCommand.kt, loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/administration/SayCommand.kt, loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/administration/SlowModeCommand.kt, loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/administration/UnbanCommand.kt, loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/administration/UnlockCommand.kt, loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/administration/UnmuteCommand.kt, loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/administration/UnwarnCommand.kt, loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/administration/WarnCommand.kt, loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/administration/WarnListCommand.kt, loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/misc/LanguageCommand.kt, loritta-discord/src/main/java/com/mrpowergamerbr/loritta/modules/AutomodModule.kt, loritta-discord/src/main/java/com/mrpowergamerbr/loritta/utils/LorittaUtilsKotlin.kt, loritta-discord/src/main/java/com/mrpowergamerbr/loritta/utils/extensions/CommandExtensions.kt, loritta-discord/src/main/java/com/mrpowergamerbr/loritta/utils/locale/LegacyBaseLocale.kt, loritta-discord/src/main/java/com/mrpowergamerbr/loritta/utils/locale/LocaleUtils.kt, loritta-discord/src/main/java/net/perfectdreams/loritta/utils/metrics/JFRExports.kt, loritta-discord/src/main/java/net/perfectdreams/loritta/utils/metrics/Prometheus.kt, loritta-plugins/lori-guild-stuff/src/main/kotlin/net/perfectdreams/loritta/plugin/loriguildstuff/commands/FastBanCommand.kt, loritta-plugins/lori-guild-stuff/src/main/kotlin/net/perfectdreams/loritta/plugin/loriguildstuff/modules/BlockBadWordsModule.kt, loritta-plugins/parallax-routes/src/main/kotlin/net/perfectdreams/loritta/plugin/parallaxroutes/routes/PutGuildBanRoute.kt, loritta-plugins/staff-lorittaban/src/main/kotlin/net/perfectdreams/loritta/plugin/stafflorittaban/listeners/CheckReactionsForPrivateSpamListener.kt
* Loritta: https://github.com/LorittaBot/Loritta/pull/2243
* Locales: https://github.com/LorittaBot/LorittaLocales/pull/104
Fixes #2240
=> Improve all moderation commands and migrate theirs locales entries.

loritta-plugins/artsy-joy-lori/src/main/kotlin/net/perfectdreams/loritta/commands/actions/modern/ActionCommands.kt
=> Fix receiver/sender on ActionCommands.kt

loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/CommandManager.kt, loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/administration/LimparCommand.kt, loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/administration/MuteCommand.kt, loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/administration/RoleIdCommand.kt, loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/administration/SayCommand.kt, loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/administration/SlowModeCommand.kt, loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/administration/UnwarnCommand.kt, loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/minecraft/SpigotMcCommand.kt, loritta-discord/src/main/java/com/mrpowergamerbr/loritta/listeners/EventLogListener.kt
This PR is related to #2262 and #2263
=> Migrate legacylocale to new

loritta-plugins/profile-designs/src/main/kotlin/net/perfectdreams/loritta/plugin/profiles/designs/Christmas2019ProfileCreator.kt, loritta-plugins/profile-designs/src/main/kotlin/net/perfectdreams/loritta/plugin/profiles/designs/CowboyProfileCreator.kt, loritta-plugins/profile-designs/src/main/kotlin/net/perfectdreams/loritta/plugin/profiles/designs/DefaultProfileCreator.kt, loritta-plugins/profile-designs/src/main/kotlin/net/perfectdreams/loritta/plugin/profiles/designs/Halloween2019ProfileCreator.kt, loritta-plugins/profile-designs/src/main/kotlin/net/perfectdreams/loritta/plugin/profiles/designs/LoriAtaProfileCreator.kt, loritta-plugins/profile-designs/src/main/kotlin/net/perfectdreams/loritta/plugin/profiles/designs/LorittaChristmas2019ProfileCreator.kt, loritta-plugins/profile-designs/src/main/kotlin/net/perfectdreams/loritta/plugin/profiles/designs/MSNProfileCreator.kt, loritta-plugins/profile-designs/src/main/kotlin/net/perfectdreams/loritta/plugin/profiles/designs/MonicaAtaProfileCreator.kt, loritta-plugins/profile-designs/src/main/kotlin/net/perfectdreams/loritta/plugin/profiles/designs/NextGenProfileCreator.kt, loritta-plugins/profile-designs/src/main/kotlin/net/perfectdreams/loritta/plugin/profiles/designs/PlainProfileCreator.kt, loritta-plugins/profile-designs/src/main/kotlin/net/perfectdreams/loritta/plugin/profiles/designs/UndertaleProfileCreator.kt
This pull request fixes https://github.com/LorittaBot/Loritta/issues/2257
=> Fix "null" while trying to show user's local experience rank

loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/economy/PagarCommand.kt, loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/social/PerfilCommand.kt
Fix https://ptb.discord.com/channels/297732013006389252/664431430159302674/782720743048740894 _(second image)_ and fix lori's about me on "+perfil".
=> Fix locale keys

loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/social/EditarXPCommand.kt, loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/utils/MoneyCommand.kt, loritta-plugins/artsy-joy-lori/src/main/kotlin/net/perfectdreams/loritta/commands/discord/GuildBannerCommand.kt
Similar to https://github.com/LorittaBot/Loritta/commit/f515b0efbeb9c0ac8ec1b375d5e5f8b90db10833
=> Fix a lot of small stuff

loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/CommandContext.kt, loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/administration/LimparCommand.kt, loritta-discord/src/main/java/com/mrpowergamerbr/loritta/utils/extensions/JDAExtensions.kt
=> Fix replies when origin message was deleted

loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/administration/SayCommand.kt
Fix https://discord.com/channels/297732013006389252/664431430159302674/782997119174311946
=> Fixed locale key

loritta-website/spicy-morenitta/src/main/kotlin/net/perfectdreams/spicymorenitta/routes/guilds/dashboard/CustomCommandsRoute.kt
In my opinion, this can be implemented instead of another command preview (#2166), after some tests I saw that adding another preview to the modal would look weird.
* Closes: #2166
=> Add command label warning to the custom commands section

loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/music/LyricsCommand.kt, loritta-plugins/artsy-joy-lori/src/main/kotlin/net/perfectdreams/loritta/commands/images/AtendenteCommand.kt
Fixed a bug report of the command "+lyrics" that when placing an invalid song Loritta returned a message with an invalid locale key.
Bug report message link: https://discord.com/channels/297732013006389252/664431430159302674/783773383858454548
Also fixed the locale key for the command description "+atendente".
=> Fixed a bug report

loritta-discord/src/main/java/net/perfectdreams/loritta/website/routes/RequiresDiscordLoginLocalizedRoute.kt
This pull request fixes #2284 issue
=> Fix Loritta's message on join DM

loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/discord/ServerInfoCommand.kt
In languages like Portuguese, "owner" has two variants for both genders: "dono" and "dona".
This PR is made to differentiate both variants of the word "owner".
To be merged with LorittaBot/LorittaLocales#136
_(PS: Thanks Arthur#0007 for the suggestion!)_
=> Differentiate both male and female 'pronouns' for guild owner

loritta-plugins/helping-hands/src/main/kotlin/net/perfectdreams/loritta/plugin/helpinghands/commands/CoinFlipBetCommand.kt
+ Closes #2303 
+ To be merged with LorittaBot/LorittaLocales#137
=> Coinflip betting confirmation to both users

loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/social/DivorceCommand.kt
https://github.com/LorittaBot/Loritta/issues/2289
=> Send DM when divorce

loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/administration/QuickPunishmentCommand.kt
Locales: https://github.com/LorittaBot/LorittaLocales/pull/152
=> Added a new message on how to enable/disable quickpunishment

loritta-plugins/lori-broker/src/main/kotlin/net/perfectdreams/loritta/plugin/loribroker/commands/BrokerSellStockCommand.kt
=> Allow to sell all of your stocks for any ticker

loritta-discord/src/main/java/net/perfectdreams/loritta/commands/vanilla/economy/TransactionsCommand.kt
Based on `+fanarts` & `+atm top`
=> Added pagination system for +transactions

loritta-discord/src/main/java/net/perfectdreams/loritta/utils/giveaway/GiveawayManager.kt
This pull request fixes something that could be mentioned by everyone, here and other roles in the draw finalization message.
=> Now Loritta does not mention everyone, here and other roles in the giveaway message

loritta-discord/src/main/java/net/perfectdreams/loritta/commands/vanilla/economy/TransactionsCommand.kt
* #2331 
* locales: https://github.com/LorittaBot/LorittaLocales/pull/155
* I had to change the number of transactions that can appear per page because of the new information added.
=> Added coinflip bet users to the "+transactions" command

loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/discord/RemoveEmojiCommand.kt
Original suggestion: https://discord.com/channels/297732013006389252/359139508681310212/794999804550709248
=> Added "+delemoji" as alias of "+deleteemoji"

loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/discord/AddEmojiCommand.kt
I added the aliases "+createemoji" and "+criaremoji" to the command "+addemoji"
=> Added new aliases for the "+addemoji" command

loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/administration/BanCommand.kt, loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/administration/KickCommand.kt, loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/administration/MuteCommand.kt, loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/administration/WarnCommand.kt
The title of the last commit came out wrong but it was supposed to be "Added a new example of how to use the multiwarn".
I created a new pull request because I closed the old one and deleted my old fork too and to remove those old commits from the pull request.
If you want me to change the reason for the punishments in the example, I will. Yes, I also don't think they would warn for raiding.
=> Added a new example of how to use the multiban/kick/mute/warn

loritta-discord/src/main/java/net/perfectdreams/loritta/website/routes/api/v1/user/PatchProfileRoute.kt
This pull request fixes a small bug in the payment reason when buying the ship effect
=> Fixed a small bug

loritta-plugins/lori-broker/src/main/kotlin/net/perfectdreams/loritta/plugin/loribroker/commands/BrokerCommand.kt, loritta-plugins/lori-broker/src/main/kotlin/net/perfectdreams/loritta/plugin/loribroker/commands/BrokerPortfolioCommand.kt
=> Add stock change percentage in the "+broker" and "+broker p" command

loritta-discord/src/main/java/net/perfectdreams/loritta/commands/vanilla/administration/BanInfoCommand.kt
Fixed when the ban had no reason and "null" appeared.
I added the locale key to this pull request: https://github.com/LorittaBot/LorittaLocales/pull/121
=> Fixed when the reason for the ban is "null"

loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/discord/RemoveEmojiCommand.kt, loritta-discord/src/main/java/net/perfectdreams/loritta/commands/vanilla/economy/TransactionsCommand.kt, loritta-discord/src/main/java/net/perfectdreams/loritta/utils/SonhosPaymentReason.kt, loritta-discord/src/main/java/net/perfectdreams/loritta/utils/WebsiteVoteUtils.kt
this pull request fix this issue: https://github.com/LorittaBot/Loritta/issues/2337 and add dbl votes to the "+transactions" command
locales: https://github.com/LorittaBot/LorittaLocales/pull/156
=> Added dbl votes to the "+transactions" command and update "+removeemoji"

loritta-discord/src/main/java/com/mrpowergamerbr/loritta/threads/BomDiaECiaThread.kt, loritta-discord/src/main/java/com/mrpowergamerbr/loritta/utils/BomDiaECia.kt, loritta-discord/src/main/java/com/mrpowergamerbr/loritta/utils/locale/Gender.kt
=> Now the gender of the words change according to your gender in BomDiaECia.kt

loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/fun/ShipCommand.kt
Related to https://github.com/LorittaBot/Loritta/issues/2345
=> ShipCommand: Now embed color will change depending on percentage

loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/social/PerfilCommand.kt
In my opinion this would be useful for Loritta's staff to get a sense of when users were banned.
Example:
=> Added the ban date if the user is banned

loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/administration/LockCommand.kt, loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/administration/UnlockCommand.kt
This pull request adds a message saying the channel is locked/unlocked
Locales: https://github.com/LorittaBot/LorittaLocales/pull/157
=> Added a message when channel is already locked/unlocked

loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/administration/WarnCommand.kt
This pull request fixes this: https://discord.com/channels/297732013006389252/664431430159302674/804411582054400050
=> Fixed DM message

loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/administration/AdminUtils.kt, loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/administration/MuteCommand.kt, loritta-plugins/artsy-joy-lori/src/main/kotlin/net/perfectdreams/loritta/commands/actions/modern/ActionCommands.kt
This pull request implements changes that fix some errors in locale keys.
=> Fixed wrong locale keys

loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/social/EditarXPCommand.kt, loritta-discord/src/main/java/net/perfectdreams/loritta/commands/vanilla/roblox/RbUserCommand.kt
This pull request adds a new alias to the "+editxp" command and adds a feature in "+rbuser" that adds a link in the embed title that redirects to the user's profile in roblox.
=> new alias and improvements in RbUserCommand

cli/src/jvmMain/kotlin/net/perfectdreams/loritta/platform/cli/LorittaCLI.kt, commands/src/commonMain/kotlin/net/perfectdreams/loritta/commands/fun/JankenponExecutor.kt, commands/src/commonMain/kotlin/net/perfectdreams/loritta/commands/fun/declarations/JankenponCommand.kt, common/src/commonMain/kotlin/net/perfectdreams/loritta/common/emotes/Emotes.kt
=> Add JankenponCommand (aka PedraPapelTesouraCommand)

cli/src/jvmMain/kotlin/net/perfectdreams/loritta/platform/cli/LorittaCLI.kt, commands/src/commonMain/kotlin/net/perfectdreams/loritta/commands/utils/MorseExecutor.kt, commands/src/commonMain/kotlin/net/perfectdreams/loritta/commands/utils/MorseFromExecutor.kt, commands/src/commonMain/kotlin/net/perfectdreams/loritta/commands/utils/MorseToExecutor.kt, commands/src/commonMain/kotlin/net/perfectdreams/loritta/commands/utils/declarations/MorseCommand.kt, common/src/commonMain/kotlin/net/perfectdreams/loritta/common/emotes/Emotes.kt, common/src/commonMain/kotlin/net/perfectdreams/loritta/common/utils/text/MorseUtils.kt
=> Add MorseCommand

discord/gateway/src/jvmMain/kotlin/net/perfectdreams/loritta/platform/kord/entities/KordMessageChannel.kt
=> Fix build errors

cli/src/jvmMain/kotlin/net/perfectdreams/loritta/platform/cli/LorittaCLI.kt, commands/src/commonMain/kotlin/net/perfectdreams/loritta/commands/utils/HelpExecutor.kt, commands/src/commonMain/kotlin/net/perfectdreams/loritta/commands/utils/declarations/HelpCommand.kt, common/src/commonMain/kotlin/net/perfectdreams/loritta/common/utils/config/LorittaConfig.kt, common/src/commonMain/kotlin/net/perfectdreams/loritta/common/utils/embed/EmbedBuilder.kt, common/src/commonMain/resources/loritta.conf, common/src/jvmMain/kotlin/net/perfectdreams/loritta/common/utils/ConfigUtils.kt, discord/gateway/src/jvmMain/kotlin/net/perfectdreams/loritta/platform/kord/LorittaKord.kt, discord/interactions/src/jvmMain/kotlin/net/perfectdreams/loritta/platform/interaktions/LorittaInteraKTions.kt, discord/interactions/src/jvmMain/kotlin/net/perfectdreams/loritta/platform/interaktions/entities/InteraKTionsMessageChannel.kt
This was tested and seems to be working fine!
=> Implement HelpCommand globally

loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/utils/WikipediaCommand.kt
=> Added page link to embed title. (WikipediaCommand)

loritta-discord/src/main/java/com/mrpowergamerbr/loritta/utils/extensions/EpochExtensions.kt
=> fixed `OffsetDateTime.humanize`

common/src/commonMain/kotlin/net/perfectdreams/loritta/cinnamon/common/emotes/Emotes.kt, discord/discord-common/src/jvmMain/kotlin/net/perfectdreams/loritta/cinnamon/platform/commands/SlashCommandExecutorWrapper.kt, pudding/client/src/main/kotlin/net/perfectdreams/loritta/cinnamon/pudding/Pudding.kt, pudding/client/src/main/kotlin/net/perfectdreams/loritta/cinnamon/pudding/entities/PuddingUserProfile.kt, pudding/client/src/main/kotlin/net/perfectdreams/loritta/cinnamon/pudding/services/UsersService.kt, pudding/client/src/main/kotlin/net/perfectdreams/loritta/cinnamon/pudding/tables/BannedUsers.kt, pudding/data/src/commonMain/kotlin/net/perfectdreams/loritta/cinnamon/pudding/data/UserBannedState.kt, resources/languages/en/commands.yml
Fixes https://github.com/LorittaBot/DreamLand/issues/119
=> Block banned users from using Loritta's slash commands

common/src/commonMain/kotlin/net/perfectdreams/loritta/cinnamon/common/emotes/Emotes.kt, common/src/commonMain/kotlin/net/perfectdreams/loritta/cinnamon/common/utils/LorittaBovespaBrokerUtils.kt, common/src/commonMain/kotlin/net/perfectdreams/loritta/cinnamon/common/utils/LorittaColors.kt, common/src/commonMain/kotlin/net/perfectdreams/loritta/cinnamon/common/utils/TransactionType.kt, discord/commands/src/jvmMain/kotlin/net/perfectdreams/loritta/cinnamon/platform/commands/CommandManager.kt, discord/commands/src/jvmMain/kotlin/net/perfectdreams/loritta/cinnamon/platform/commands/ComponentExecutorIds.kt, discord/commands/src/jvmMain/kotlin/net/perfectdreams/loritta/cinnamon/platform/commands/economy/ChangeTransactionFilterSelectMenuExecutor.kt, discord/commands/src/jvmMain/kotlin/net/perfectdreams/loritta/cinnamon/platform/commands/economy/ChangeTransactionPageButtonClickExecutor.kt, discord/commands/src/jvmMain/kotlin/net/perfectdreams/loritta/cinnamon/platform/commands/economy/ChangeTransactionPageData.kt, discord/commands/src/jvmMain/kotlin/net/perfectdreams/loritta/cinnamon/platform/commands/economy/TransactionListData.kt, discord/commands/src/jvmMain/kotlin/net/perfectdreams/loritta/cinnamon/platform/commands/economy/TransactionsExecutor.kt, discord/commands/src/jvmMain/kotlin/net/perfectdreams/loritta/cinnamon/platform/commands/economy/declarations/TransactionsCommand.kt, pudding/client/src/main/kotlin/net/perfectdreams/loritta/cinnamon/pudding/Pudding.kt, pudding/client/src/main/kotlin/net/perfectdreams/loritta/cinnamon/pudding/services/BovespaBrokerService.kt, pudding/client/src/main/kotlin/net/perfectdreams/loritta/cinnamon/pudding/services/Service.kt, pudding/client/src/main/kotlin/net/perfectdreams/loritta/cinnamon/pudding/services/SonhosService.kt, pudding/client/src/main/kotlin/net/perfectdreams/loritta/cinnamon/pudding/tables/BrokerSonhosTransactionsLog.kt, pudding/data/src/commonMain/kotlin/net/perfectdreams/loritta/cinnamon/pudding/data/SonhosTransaction.kt, resources/languages/en/commands/transactions.yml
Allows users to see their sonhos' transactions
=> Add `/transactions`

common/src/commonMain/kotlin/net/perfectdreams/loritta/cinnamon/common/emotes/Emotes.kt, discord/commands/src/jvmMain/kotlin/net/perfectdreams/loritta/cinnamon/platform/commands/CommandManager.kt, discord/commands/src/jvmMain/kotlin/net/perfectdreams/loritta/cinnamon/platform/commands/economy/DailyExecutor.kt, discord/commands/src/jvmMain/kotlin/net/perfectdreams/loritta/cinnamon/platform/commands/economy/declarations/DailyCommand.kt, discord/discord-common/src/jvmMain/kotlin/net/perfectdreams/loritta/cinnamon/platform/utils/WebhookUtils.kt, resources/languages/en/commands/daily.yml
=> Add `/daily`

discord/commands/src/jvmMain/kotlin/net/perfectdreams/loritta/cinnamon/platform/commands/CommandManager.kt, discord/commands/src/jvmMain/kotlin/net/perfectdreams/loritta/cinnamon/platform/commands/utils/CalculatorExecutor.kt, discord/commands/src/jvmMain/kotlin/net/perfectdreams/loritta/cinnamon/platform/commands/utils/CalculatorPreprocessAutocompleteExecutor.kt, discord/discord-common/src/jvmMain/kotlin/net/perfectdreams/loritta/cinnamon/platform/commands/options/SlashCommandOptionsWrapper.kt
=> Add autocomplete on the `/calc`, to automatically validate and show the user the result of the calculation

common/src/commonMain/kotlin/net/perfectdreams/loritta/cinnamon/common/emotes/Emotes.kt, common/src/commonMain/kotlin/net/perfectdreams/loritta/cinnamon/common/utils/DivineInterventionTransactionEntryAction.kt, common/src/commonMain/kotlin/net/perfectdreams/loritta/cinnamon/common/utils/TransactionType.kt, discord/commands/src/jvmMain/kotlin/net/perfectdreams/loritta/cinnamon/platform/commands/economy/TransactionsExecutor.kt, pudding/client/src/main/kotlin/net/perfectdreams/loritta/cinnamon/pudding/Pudding.kt, pudding/client/src/main/kotlin/net/perfectdreams/loritta/cinnamon/pudding/services/Service.kt, pudding/client/src/main/kotlin/net/perfectdreams/loritta/cinnamon/pudding/services/SonhosService.kt, pudding/client/src/main/kotlin/net/perfectdreams/loritta/cinnamon/pudding/tables/CoinFlipBetMatchmakingResults.kt, pudding/client/src/main/kotlin/net/perfectdreams/loritta/cinnamon/pudding/tables/CoinFlipBetSonhosTransactionsLog.kt, pudding/client/src/main/kotlin/net/perfectdreams/loritta/cinnamon/pudding/tables/DivineInterventionSonhosTransactionsLog.kt, pudding/client/src/main/kotlin/net/perfectdreams/loritta/cinnamon/pudding/tables/EmojiFightMatches.kt, pudding/client/src/main/kotlin/net/perfectdreams/loritta/cinnamon/pudding/tables/EmojiFightMatchmakingResults.kt, pudding/client/src/main/kotlin/net/perfectdreams/loritta/cinnamon/pudding/tables/EmojiFightParticipants.kt, pudding/client/src/main/kotlin/net/perfectdreams/loritta/cinnamon/pudding/tables/EmojiFightSonhosTransactionsLog.kt, pudding/client/src/main/kotlin/net/perfectdreams/loritta/cinnamon/pudding/tables/PaymentSonhosTransactionResults.kt, pudding/client/src/main/kotlin/net/perfectdreams/loritta/cinnamon/pudding/tables/PaymentSonhosTransactionsLog.kt, pudding/client/src/main/kotlin/net/perfectdreams/loritta/cinnamon/pudding/tables/SonhosBundlePurchaseSonhosTransactionsLog.kt, pudding/client/src/main/kotlin/net/perfectdreams/loritta/cinnamon/pudding/tables/SonhosBundles.kt, pudding/data/src/commonMain/kotlin/net/perfectdreams/loritta/cinnamon/pudding/data/SonhosTransaction.kt, resources/languages/en/commands/transactions.yml
Implements new transaction types (#2513), I'm also implementing support on Loritta Legacy to already insert data using the new transaction tables, allowing them to show up on `/transactions`:
* Payments
* Coin Flip Bet
* Emoji Fight Bet
* Divine Intervention
* Bundle Purchase
=> Add new transaction reasons

common/src/commonMain/kotlin/net/perfectdreams/loritta/cinnamon/common/emotes/Emotes.kt, common/src/commonMain/kotlin/net/perfectdreams/loritta/cinnamon/common/utils/GACampaigns.kt, discord/commands/src/jvmMain/kotlin/net/perfectdreams/loritta/cinnamon/platform/commands/CommandManager.kt, discord/commands/src/jvmMain/kotlin/net/perfectdreams/loritta/cinnamon/platform/commands/discord/LorittaInfoExecutor.kt, discord/commands/src/jvmMain/kotlin/net/perfectdreams/loritta/cinnamon/platform/commands/discord/declarations/LorittaCommand.kt, discord/discord-common/src/jvmMain/kotlin/net/perfectdreams/loritta/cinnamon/platform/LorittaCinnamon.kt, discord/gateway/src/main/kotlin/net/perfectdreams/loritta/cinnamon/platform/gateway/LorittaCinnamonGateway.kt, discord/web-server/src/main/kotlin/net/perfectdreams/loritta/cinnamon/platform/webserver/LorittaCinnamonWebServer.kt, pudding/client/src/main/kotlin/net/perfectdreams/loritta/cinnamon/pudding/services/ExecutedInteractionsLogService.kt, pudding/client/src/main/kotlin/net/perfectdreams/loritta/cinnamon/pudding/services/StatsService.kt, resources/languages/en/commands/loritta.yml, web/showtime/backend/src/main/kotlin/net/perfectdreams/showtime/backend/PublicApplicationCommands.kt
The image in the embed is a placeholder, but it is kinda charming ngl
=> Add `/loritta info`

resources/languages/en/website.yml, web/showtime/backend/src/main/kotlin/net/perfectdreams/showtime/backend/DefaultRoutes.kt, web/showtime/backend/src/main/kotlin/net/perfectdreams/showtime/backend/routes/ContactRoute.kt, web/showtime/backend/src/main/kotlin/net/perfectdreams/showtime/backend/views/ContactView.kt, web/showtime/backend/src/main/kotlin/net/perfectdreams/showtime/backend/views/NavbarView.kt, web/showtime/backend/src/main/sass/components/_contact-us-wrapper.scss, web/showtime/backend/src/main/sass/style.scss, web/showtime/web-common/src/commonMain/kotlin/net/perfectdreams/dokyo/RoutePath.kt
Because I think it would be nice
=> Add business contact page

buildSrc/src/main/kotlin/Versions.kt, platforms/discord/legacy/src/main/java/com/mrpowergamerbr/loritta/Loritta.kt, platforms/discord/legacy/src/main/java/com/mrpowergamerbr/loritta/listeners/ChannelListener.kt, platforms/discord/legacy/src/main/java/com/mrpowergamerbr/loritta/listeners/DiscordListener.kt, platforms/discord/legacy/src/main/java/com/mrpowergamerbr/loritta/listeners/GatewayEventRelayerListener.kt
This is a super hacky hack that still needs to be really tested
=> Relay Discord Gateway Events

discord/loritta-bot-common/src/main/kotlin/net/perfectdreams/loritta/cinnamon/discord/interactions/vanilla/social/EditXpExecutor.kt, discord/loritta-bot-common/src/main/kotlin/net/perfectdreams/loritta/cinnamon/discord/interactions/vanilla/social/declarations/XpCommand.kt, discord/loritta-bot-common/src/main/kotlin/net/perfectdreams/loritta/morenitta/LorittaBot.kt, resources/languages/pt/commands.yml, resources/languages/pt/commands/xpedit.yml
* New feature: EditXp in Slash Command version has 3 modes (Add, Remove, Set).
=> Migrate `+editxp` command to Slash Commands (`/xp edit`)

web/showtime/backend/src/main/kotlin/net/perfectdreams/loritta/cinnamon/showtime/backend/views/StaffView.kt
Also includes me... Bye Loritta!
Also² adding a new staffer, welcome Srta. Paum!
=> Removing demoted staffers.

common/src/commonMain/kotlin/net/perfectdreams/loritta/cinnamon/emotes/Emotes.kt, discord/loritta-bot-common/src/main/kotlin/net/perfectdreams/loritta/cinnamon/discord/interactions/vanilla/social/TransferXpExecutor.kt, resources/languages/pt/commands/xptransfer.yml
* Add verification in command to avoid duplicate xp bug when user1 is same as user2.
* Add two new emotes in Loritta, `lori_fire` & `lori_fine`.
=> Add verification in `/xp transfer` to avoid duplicate user xp.

resources/languages/pt/commands/broker.yml
Updated sentence structure to ensure proper subject-verb agreement in the stock trading advice. This improves clarity and readability.
- Update the `broker.yml` file located in `resources/languages/pt/commands/` to correct grammatical errors and improve sentence structure for more coherent language.
=> fix: subject-verb agreement

.gitignore, loritta-bot-discord/src/main/kotlin/net/perfectdreams/loritta/morenitta/interactions/vanilla/discord/GuildCommand.kt, loritta-bot-discord/src/main/kotlin/net/perfectdreams/loritta/morenitta/interactions/vanilla/discord/MessageStickerCommand.kt, resources/languages/pt/commands/guild.yml
Also fixed GIF display while ~~stealing~~ getting the GIF from a message.
Also² adjusted autocomplete display when there are two stickers with the same name
Also³ added Loritta's Config to the `.gitignore`
=> Enhanced sticker feedback

docs/SELF-HOSTING.md
Here are some tips for those who want to self-host Loritta and don't know where to start.
=> Adding SELF-HOSTING.md
