src/main/java/com/mrpowergamerbr/loritta/website/views/subviews/api/APIGetRssFeedTitleView.kt

Hi.
This PR should solve issues with Loritta not able to read Atom feeds of MediaWiki-based websites (Like Wikipedia). An example would be [Recent Changes Atom](https://en.wikipedia.org/w/api.php?hidebots=1&hidecategorization=1&hideWikibase=1&urlversion=1&days=7&limit=50&target=Main_Page&action=feedrecentchanges&feedformat=atom).
With this change, `summary` tag should be accepted as `{description}`.
Please notify me when you're able to push this change to the running version.
Best Regards

Support MediaWiki Atom feeds

---

pom.xml

Elas foram removidas nas versões mais recentes do JDK, enquanto dá para rodar sem elas (adicionando `--add.module`, compilar a Lori em um JDK mais recente dá erro)

Adicionar as dependências do JAXB

---

src/main/java/com/mrpowergamerbr/loritta/Loritta.kt
src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/magic/PluginsCommand.kt
src/main/java/com/mrpowergamerbr/loritta/plugin/InvalidPluginException.kt
src/main/java/com/mrpowergamerbr/loritta/plugin/LorittaPlugin.kt
src/main/java/com/mrpowergamerbr/loritta/plugin/PluginManager.kt
src/main/java/net/perfectdreams/commands/loritta/LorittaCommandManager.kt

Um sistema de plugins, atualmente bem básico: Plugins podem registrar comandos.
Cada plugin precisa ter um `plugin.yml` com o `name` (nome do plugin) e `main` (classe principal do plugin)
Assim será possível recarregar plugins durante o runtime da Lori, permitindo adicionar novos comandos e funcionalidades sem precisar reiniciar ela inteira (Ou seja, teria o `Core` (que é a Loritta principal) e os `plugins`, que implementam funcionalidades adicionais nela)

Adicionar sistema de plugins

---

src/main/java/com/mrpowergamerbr/loritta/Loritta.kt
src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/magic/PluginsCommand.kt
src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/misc/MagicPingCommand.kt
src/main/java/com/mrpowergamerbr/loritta/plugin/LorittaPlugin.kt
src/main/java/com/mrpowergamerbr/loritta/utils/LoriReply.kt
src/main/java/com/mrpowergamerbr/loritta/utils/LorittaUser.kt
src/main/java/com/mrpowergamerbr/loritta/utils/LorittaUtilsKotlin.kt
src/main/java/com/mrpowergamerbr/loritta/utils/MessageUtils.kt
src/main/java/net/perfectdreams/commands/loritta/annotation/LorittaArgumentType.kt
src/main/java/net/perfectdreams/loritta/api/commands/CommandException.kt
src/main/java/net/perfectdreams/loritta/api/commands/LorittaCommand.kt
src/main/java/net/perfectdreams/loritta/api/commands/LorittaCommandContext.kt
src/main/java/net/perfectdreams/loritta/api/commands/LorittaCommandManager.kt
src/main/java/net/perfectdreams/loritta/api/commands/annotation/InjectLoritta.kt
src/main/java/net/perfectdreams/loritta/api/commands/annotation/LorittaArgumentType.kt
src/main/java/net/perfectdreams/loritta/api/entities/Message.kt
src/main/java/net/perfectdreams/loritta/api/entities/User.kt
src/main/java/net/perfectdreams/loritta/api/impl/DiscordMessage.kt
src/main/java/net/perfectdreams/loritta/api/impl/DiscordUser.kt

Plugins devem ser feitos utilizando a Loritta API, em vez de usar a API do JDA.
Isto é uma "pseudo-continuação" da [Loritta Cinnamon](https://github.com/LorittaBot/LorittaCinnamon), permitindo que futuramente a Loritta suporte mais plataformas (em vez de somente o Discord)
Atualmente apenas duas classes existem: `Message` e `User`, mas isto já deve ser bom o suficiente para suportar o básico que a gente precisa.
Se acontecer um "oh no, precisamos implementar algo que ainda não suporta na API!!!", `(message as DiscordMessage).handle` retorna a versão original da mensagem.

Implementação inicial da Loritta API

---

src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/actions/SlapCommand.kt

Arrumar isso (estou falando da parte de "`@Nightdavisao deu um tapa bem merecido em @Loritta`", o que era pra ser o inverso):

Pequeno fix no +slap

---

loritta-core/src/main/java/net/perfectdreams/loritta/utils/FeatureFlags.kt

O jeito atual pega se a Feature Flag está ativada apenas uma vez e reutiliza ela para *sempre*.
Isso dá problemas caso tenha que ativar/desativar feature flags sem precisar reiniciar a Lori.
Para corrigir, o pull request altera para um `get() = FeatureFlag...`, ou seja, toda hora que for utilizado `FeatureFlag.FF_NAME`, sempre será pego utilizando `isEnabled(...)`

Sempre verifique as feature flags ativadas na configuração, em vez de apenas verificar uma vez e reutilizar o mesmo valor várias vezes

---

loritta-discord/src/main/java/com/mrpowergamerbr/loritta/listeners/DiscordListener.kt
loritta-discord/src/main/java/com/mrpowergamerbr/loritta/modules/InviteLinkModule.kt

Because we can check when a invite is created/deleted, we can change the expiration to be more lenient, since the cache will be invalidated when they are created/deleted
Fixes #2099

Invalidate invite cache when a invite is created/deleted, change to expire after access

---

loritta-plugins/lori-guild-stuff/src/main/kotlin/net/perfectdreams/loritta/plugin/loriguildstuff/commands/FastBanCommand.kt

This PR does the following:
- Fixes the `index out of bounds for length` error;
- Names of avaliable punishment reasons are now dynamically loaded, removing the need to manually edit messages every time you add a new punishment option;
- Simplifies code by switching from if statments to the elvis operator `?:`.

FastBanCommand fixes & more stuff

---

loritta-plugins/lori-guild-stuff/src/main/kotlin/net/perfectdreams/loritta/plugin/loriguildstuff/commands/ColorCommand.kt

This is useful because there was a bug when you don't select any color and the message changes the formatting

Don't show selected color if it's unavailable

---

loritta-plugins/fortnite-stuff/src/main/kotlin/net/perfectdreams/loritta/plugin/fortnite/FortniteStuff.kt
loritta-plugins/fortnite-stuff/src/main/kotlin/net/perfectdreams/loritta/plugin/fortnite/UpdateStoreItemsTask.kt
loritta-plugins/fortnite-stuff/src/main/kotlin/net/perfectdreams/loritta/plugin/fortnite/commands/fortnite/FortniteItemCommand.kt
loritta-plugins/fortnite-stuff/src/main/kotlin/net/perfectdreams/loritta/plugin/fortnite/commands/fortnite/FortniteNewsCommand.kt
loritta-plugins/fortnite-stuff/src/main/kotlin/net/perfectdreams/loritta/plugin/fortnite/commands/fortnite/FortniteNotifyCommand.kt
loritta-plugins/fortnite-stuff/src/main/kotlin/net/perfectdreams/loritta/plugin/fortnite/commands/fortnite/FortniteStatsCommand.kt

A lot of commands broke because the API I was using is now unmaintained.
This changes the commands to use https://fortnite-api.com
**Stuff that will break:**
* The item IDs changed, so all notifications will be wiped.
* Can't get Team Rumble stats anymore
**Stuff that needs to be checked:**
* Item Shop notifications and broadcasts

Fix Fortnite-related commands

---

loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/economy/PagarCommand.kt

If the user placed an amount of dreams above what he had at the time of transferring dreams, the loritta would return this: "!!{commands.economy.pay..insufficientFunds}!!"

Fix locale key in PagarCommand.kt

---

loritta-plugins/lori-broker/src/main/kotlin/net/perfectdreams/loritta/plugin/loribroker/commands/BrokerPortfolioCommand.kt

It was showing the stocks price, not the stocks selling price, that was fixed.

Fix selling price field on broker portfolio

---

loritta-discord/src/main/java/com/mrpowergamerbr/loritta/listeners/MessageListener.kt

This pull request fixes this issue: #2312

Loritta now uses the name of the role in the response

---

loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/utils/DicioCommand.kt

This pull request fixes this issue: https://github.com/LorittaBot/Loritta/issues/2372

Added the correct meaning to the "+dicio" embed title

---

loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/economy/LigarCommand.kt
loritta-discord/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/social/MarryCommand.kt
loritta-discord/src/main/java/com/mrpowergamerbr/loritta/dao/Profile.kt
loritta-discord/src/main/java/com/mrpowergamerbr/loritta/threads/RaffleThread.kt
loritta-discord/src/main/java/net/perfectdreams/loritta/utils/PaymentUtils.kt
loritta-discord/src/main/java/net/perfectdreams/loritta/website/routes/api/v1/economy/GetLoriDailyRewardRoute.kt
loritta-discord/src/main/java/net/perfectdreams/loritta/website/routes/api/v1/economy/PostBuyDailyShopItemRoute.kt
loritta-discord/src/main/java/net/perfectdreams/loritta/website/routes/api/v1/economy/PostTransferBalanceExternalRoute.kt
loritta-discord/src/main/java/net/perfectdreams/loritta/website/routes/api/v1/loritta/PostRaffleStatusRoute.kt
loritta-discord/src/main/java/net/perfectdreams/loritta/website/routes/api/v1/user/PatchProfileRoute.kt
loritta-plugins/helping-hands/src/main/kotlin/net/perfectdreams/loritta/plugin/helpinghands/commands/GuessNumberCommand.kt
loritta-plugins/lori-broker/src/main/kotlin/net/perfectdreams/loritta/plugin/loribroker/commands/BrokerBuyStockCommand.kt
loritta-plugins/lori-broker/src/main/kotlin/net/perfectdreams/loritta/plugin/loribroker/commands/BrokerCommand.kt
loritta-plugins/lori-broker/src/main/kotlin/net/perfectdreams/loritta/plugin/loribroker/commands/BrokerSellStockCommand.kt

This adds a function that merges sonhos add/take with the add sonhos transaction log
A very small refactor that helps a lot when developing stuff that handles sonhos
Keep in mind that this does *not* handle all the stuff that Loritta handles with sonhos (Example: `+pay` adds and removes sonhos from users and adds a single sonhos transactions), this could be added later

Refactor sonhos add/take + sonhos transactions

---

.github/workflows/build.yml
microservices/stats-collector/build.gradle.kts
microservices/stats-collector/src/main/kotlin/net/perfectdreams/loritta/cinnamon/microservices/statscollector/StatsCollector.kt
microservices/stats-collector/src/main/kotlin/net/perfectdreams/loritta/cinnamon/microservices/statscollector/StatsCollectorLauncher.kt
microservices/stats-collector/src/main/kotlin/net/perfectdreams/loritta/cinnamon/microservices/statscollector/endpoints/DatabaseStatsSender.kt
microservices/stats-collector/src/main/kotlin/net/perfectdreams/loritta/cinnamon/microservices/statscollector/endpoints/DiscordBotsStatsSender.kt
microservices/stats-collector/src/main/kotlin/net/perfectdreams/loritta/cinnamon/microservices/statscollector/endpoints/StatsSender.kt
microservices/stats-collector/src/main/kotlin/net/perfectdreams/loritta/cinnamon/microservices/statscollector/endpoints/TopggStatsSender.kt
microservices/stats-collector/src/main/kotlin/net/perfectdreams/loritta/cinnamon/microservices/statscollector/utils/LorittaLegacyStatusResponse.kt
microservices/stats-collector/src/main/kotlin/net/perfectdreams/loritta/cinnamon/microservices/statscollector/utils/LorittaStatsCollector.kt
microservices/stats-collector/src/main/kotlin/net/perfectdreams/loritta/cinnamon/microservices/statscollector/utils/RunnableCoroutineWrapper.kt
microservices/stats-collector/src/main/kotlin/net/perfectdreams/loritta/cinnamon/microservices/statscollector/utils/StatsTasks.kt
microservices/stats-collector/src/main/kotlin/net/perfectdreams/loritta/cinnamon/microservices/statscollector/utils/config/DiscordBotsConfig.kt
microservices/stats-collector/src/main/kotlin/net/perfectdreams/loritta/cinnamon/microservices/statscollector/utils/config/PuddingConfig.kt
microservices/stats-collector/src/main/kotlin/net/perfectdreams/loritta/cinnamon/microservices/statscollector/utils/config/RootConfig.kt
microservices/stats-collector/src/main/kotlin/net/perfectdreams/loritta/cinnamon/microservices/statscollector/utils/config/TopggConfig.kt
microservices/stats-collector/src/main/resources/analytics-collector.conf
pudding/client/src/main/kotlin/net/perfectdreams/loritta/cinnamon/pudding/Pudding.kt
pudding/client/src/main/kotlin/net/perfectdreams/loritta/cinnamon/pudding/services/StatsService.kt
pudding/client/src/main/kotlin/net/perfectdreams/loritta/cinnamon/pudding/tables/GuildCountStats.kt
settings.gradle.kts

Collects guild count data from Loritta (Legacy) and sends it to top.gg, Discord Bots and to Loritta's own database, useful for when a `/botinfo` is implemented (Because Loritta shows the current guild count there)
Fixes #2429

Add stats collector microservice

---

buildSrc/src/main/kotlin/Versions.kt
loritta-plugins/helping-hands/src/main/kotlin/net/perfectdreams/loritta/plugin/helpinghands/commands/CoinFlipBetCommand.kt
loritta-plugins/helping-hands/src/main/kotlin/net/perfectdreams/loritta/plugin/helpinghands/utils/EmojiFight.kt
loritta-serializable-commons/build.gradle.kts
platforms/discord/legacy/build.gradle.kts
platforms/discord/legacy/src/main/java/com/mrpowergamerbr/loritta/commands/vanilla/magic/LoriServerListConfigCommand.kt
platforms/discord/legacy/src/main/java/net/perfectdreams/loritta/website/routes/api/v1/callbacks/PostPerfectPaymentsCallbackRoute.kt
platforms/discord/legacy/src/main/java/net/perfectdreams/loritta/website/routes/api/v1/loritta/PostTransferBalanceRoute.kt

Use Cinnamon/Pudding transactions in Loritta Legacy

---

buildSrc/src/main/kotlin/Versions.kt
discord/commands/src/jvmMain/kotlin/net/perfectdreams/loritta/cinnamon/platform/commands/CommandManager.kt
discord/commands/src/jvmMain/kotlin/net/perfectdreams/loritta/cinnamon/platform/commands/ComponentExecutorIds.kt
discord/commands/src/jvmMain/kotlin/net/perfectdreams/loritta/cinnamon/platform/commands/discord/SwitchToGlobalAvatarExecutor.kt
discord/commands/src/jvmMain/kotlin/net/perfectdreams/loritta/cinnamon/platform/commands/discord/SwitchToGuildProfileAvatarExecutor.kt
discord/commands/src/jvmMain/kotlin/net/perfectdreams/loritta/cinnamon/platform/commands/discord/UserAvatarExecutor.kt
discord/commands/src/jvmMain/kotlin/net/perfectdreams/loritta/cinnamon/platform/commands/discord/UserDataUtils.kt
discord/commands/src/jvmMain/kotlin/net/perfectdreams/loritta/cinnamon/platform/commands/fun/HungerGamesExecutor.kt
discord/commands/src/jvmMain/kotlin/net/perfectdreams/loritta/cinnamon/platform/commands/fun/ShipExecutor.kt
discord/commands/src/jvmMain/kotlin/net/perfectdreams/loritta/cinnamon/platform/commands/images/SadRealityExecutor.kt
discord/discord-common/src/jvmMain/kotlin/net/perfectdreams/loritta/cinnamon/platform/LorittaCinnamon.kt
discord/discord-common/src/jvmMain/kotlin/net/perfectdreams/loritta/cinnamon/platform/commands/SlashCommandExecutorWrapper.kt
discord/discord-common/src/jvmMain/kotlin/net/perfectdreams/loritta/cinnamon/platform/utils/ContextStringToUserInfoConverter.kt
resources/languages/en/commands/user.yml

Fixes #2530
For now only avatar switching is implemented.
Changes were also made in other classes, because Discord InteraKTions was updated to handle members' avatars.

Add button to switch between the user's global avatar and guild avatar

---

buildSrc/src/main/kotlin/Versions.kt
common/src/commonMain/kotlin/net/perfectdreams/loritta/cinnamon/common/emotes/Emotes.kt
common/src/commonMain/kotlin/net/perfectdreams/loritta/cinnamon/common/utils/JsonIgnoreMissingFields.kt
common/src/commonMain/kotlin/net/perfectdreams/loritta/cinnamon/common/utils/LorittaColors.kt
discord/commands/src/jvmMain/kotlin/net/perfectdreams/loritta/cinnamon/platform/commands/CommandManager.kt
discord/commands/src/jvmMain/kotlin/net/perfectdreams/loritta/cinnamon/platform/commands/ComponentExecutorIds.kt
discord/commands/src/jvmMain/kotlin/net/perfectdreams/loritta/cinnamon/platform/commands/discord/avatar/MessageTargetType.kt
discord/commands/src/jvmMain/kotlin/net/perfectdreams/loritta/cinnamon/platform/commands/discord/avatar/SwitchToGlobalAvatarExecutor.kt
discord/commands/src/jvmMain/kotlin/net/perfectdreams/loritta/cinnamon/platform/commands/discord/avatar/SwitchToGuildProfileAvatarExecutor.kt
discord/commands/src/jvmMain/kotlin/net/perfectdreams/loritta/cinnamon/platform/commands/discord/avatar/UserAvatarExecutor.kt
discord/commands/src/jvmMain/kotlin/net/perfectdreams/loritta/cinnamon/platform/commands/discord/avatar/UserDataUtils.kt
discord/commands/src/jvmMain/kotlin/net/perfectdreams/loritta/cinnamon/platform/commands/discord/declarations/UserCommand.kt
discord/commands/src/jvmMain/kotlin/net/perfectdreams/loritta/cinnamon/platform/commands/discord/declarations/UserInfoUserCommand.kt
discord/commands/src/jvmMain/kotlin/net/perfectdreams/loritta/cinnamon/platform/commands/discord/info/GuildMemberPermissionsData.kt
discord/commands/src/jvmMain/kotlin/net/perfectdreams/loritta/cinnamon/platform/commands/discord/info/ShowGuildMemberPermissionsExecutor.kt
discord/commands/src/jvmMain/kotlin/net/perfectdreams/loritta/cinnamon/platform/commands/discord/info/UserInfoExecutor.kt
discord/commands/src/jvmMain/kotlin/net/perfectdreams/loritta/cinnamon/platform/commands/discord/info/UserInfoSlashExecutor.kt
discord/commands/src/jvmMain/kotlin/net/perfectdreams/loritta/cinnamon/platform/commands/discord/info/UserInfoUserExecutor.kt
discord/discord-common/build.gradle.kts
discord/discord-common/src/main/kotlin/net/perfectdreams/loritta/cinnamon/platform/LorittaCinnamon.kt
discord/discord-common/src/main/kotlin/net/perfectdreams/loritta/cinnamon/platform/utils/DiscordCacheService.kt
discord/discord-common/src/main/kotlin/net/perfectdreams/loritta/cinnamon/platform/utils/PuddingExtensions.kt
microservices/discord-gateway-events-processor/src/main/kotlin/net/perfectdreams/loritta/cinnamon/microservices/discordgatewayeventsprocessor/DiscordGatewayEventsProcessor.kt
microservices/discord-gateway-events-processor/src/main/kotlin/net/perfectdreams/loritta/cinnamon/microservices/discordgatewayeventsprocessor/modules/DiscordCacheModule.kt
microservices/discord-gateway-events-processor/src/main/kotlin/net/perfectdreams/loritta/cinnamon/microservices/discordgatewayeventsprocessor/utils/EventAnalyticsTask.kt
pudding/client/src/main/kotlin/net/perfectdreams/loritta/cinnamon/pudding/Pudding.kt
pudding/client/src/main/kotlin/net/perfectdreams/loritta/cinnamon/pudding/tables/cache/DiscordGuildRoles.kt
resources/languages/en/commands/user.yml

This commit adds the `/user info` command and the "View information" user command.
This also adds roles entity caching on the database, because `/user info` requires it for the:
* Role Position
* Role Color
I'm still not sure if this will work, but hey! Better test it out and see what happens right? At least if the caching system breaks, the command should still work without any issues since it isn't required for it to work.

Add `/user info`, add Discord entities caching

---

buildSrc/src/main/kotlin/SassTask.kt

Now adding MacOsX as supported OS for development the `dart-sass:1.35.2` seems to run in Rosetta for M1 macs, but still works, tested on a M1 mac.
For a directly ARM chip support (instead using Rosetta for translating x64) might be a good idea in the future migrate to at least [Dart Sass 1.49.11](https://github.com/sass/dart-sass/releases/tag/1.49.11).

[LorittaBot#2629] Fix Unsupported OS when running LorittaLauncher with MacOsX

---

loritta-bot-discord/src/main/kotlin/net/perfectdreams/loritta/morenitta/api/commands/CommandException.kt
loritta-bot-discord/src/main/kotlin/net/perfectdreams/loritta/morenitta/api/commands/SilentCommandException.kt
loritta-bot-discord/src/main/kotlin/net/perfectdreams/loritta/morenitta/interactions/commands/CommandException.kt

Removes stack trace generation, cause & suppression tracking and message storage from exceptions
This increases the performance of command failure (`context.fail`) by ~16-20 times.
Sources:
https://mattwarren.org/2016/12/20/Why-Exceptions-should-be-Exceptional/
https://www.baeldung.com/java-exceptions-performance

Optimize exception generation during command execution
